server.port=8090
spring.datasource.url=jdbc:mariadb://app_db:3306/unededucaanalisis
# spring.datasource.url=jdbc:mariadb://localhost:3306/unededucaanalisis
spring.datasource.username=root
spring.datasource.password=mypass
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
pfgamm.data.rutaficheros=
pfgamm.data.ficherografo=ficheroGrafo.gml
pfgamm.data.ficheroForo=test1.csv